import os

class ConfigManager:
    @staticmethod
    def ensure_eula(server_dir: str):
        """Creates or updates eula.txt to accept the EULA."""
        eula_path = os.path.join(server_dir, "eula.txt")
        # Always overwrite or create to ensure true
        with open(eula_path, "w") as f:
            f.write("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).\n")
            f.write("eula=true\n")
            
    @staticmethod
    def set_property(server_dir: str, key: str, value: str):
        """Updates a specific property in server.properties."""
        props_path = os.path.join(server_dir, "server.properties")
        properties = {}
        
        # Read existing
        if os.path.exists(props_path):
            with open(props_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        if "=" in line:
                            k, v = line.split("=", 1)
                            properties[k.strip()] = v.strip()
                            
        # Update
        properties[key] = value
        
        # Write back
        with open(props_path, "w") as f:
            f.write("#Minecraft server properties\n")
            f.write("#Auto-generated by MCSM\n")
            for k, v in properties.items():
                f.write(f"{k}={v}\n")

    @staticmethod
    def get_property(server_dir: str, key: str) -> str:
        props_path = os.path.join(server_dir, "server.properties")
        if os.path.exists(props_path):
            with open(props_path, "r") as f:
                for line in f:
                    if line.strip().startswith(f"{key}="):
                        return line.split("=", 1)[1].strip()
        return None
